version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-app}
            - MYSQL_USER=${MYSQL_USER:-app}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-app}
        ports:
            - '${MYSQL_PORT:-3306}:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '${HTTP_PORT:-80}:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
